sudo: required
language: ruby
services:
  - docker
before_install:
  - gem update bundler

rvm:
  - 1.9.3	
  - 2.0.*
  - 2.1.*
  - 2.2.*
  - 2.3.*
  - 2.4.*

gemfile:
  - Gemfile
  - Gemfile.fluentd.0.12

after_script:
  - docker-compose build
  - docker-compose run builder ./run_appraisal.sh

  
