sudo: required
language: ruby
services:
  - docker
before_install:
  - gem update bundler

rvm:
  - 2.1.*
  - 2.2.*
  - 2.3.*
  - 2.4.*
  - 2.5.*

gemfile:
  - Gemfile

after_script:
  - bundle exec rake build
  - sh run_docker_test.sh
