name: CI on Linux

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: [2.1.x, 2.2.x, 2.3.x, 2.4.x, 2.5.x, 2.6.x, 2.7.x]
      - name: Install dependencies
        run: bundle install
#      - name: build
#        run: bundle exec rake
      - name: test
        run: |
          docker-compose build
          docker-compose run -T builder ./run_appraisal.sh
